services:
  rxbot:
    build: .
    container_name: rxbot
    volumes:
      - ./log:/app/log # Logs persistentes
    env_file:
      - ./bot/.env
    environment:
      NODE_ENV: production
    restart: unless-stopped